### ISSUE TITLE
Question about changing the name of it in discord, (Feature Request Kinda)

### ISSUE THREAD

**Issue by jabanayt** [SayakMukhopadhyay/EDMC-Discord-Presence#1]
Hi,
this may be a weird question but i would like to know if there is possibly a easy/not to hard way to change the name of the "EDMC Discord Presence" in discord to something else more like, "Elite Dangerous", so that people can instantly see that i am playing it.
![screen shot 2018-06-27 at 10 29 12 pm](https://user-images.githubusercontent.com/35419583/41968801-8c2d892c-7a59-11e8-961c-f0dff52151b8.png)

**Comment by SayakMukhopadhyay** [comment]
Its not possible from the User perspective to change that name. The reason why I didn't put the name to `Elite Dangerous` is that I didn't want to face any repercussion for using a Trademark. Technically the discord presence is generated by the game displaying it but in this case EDMC generates it. So, the discord presence code running in EDMC showing Elite Dangerous can be a huge legal pitfall for me as well as EDMC.

I realise that this is not the answer you were expecting but legalities forces our hands sometimes.

**Comment by KairuByte** [comment]
This is a little old, and there are existing workarounds, but a potential way around the legal aspect would be to pass the data being presented by the game through during runtime. That way you can just throw a user option into the settings to allow cloning the game name, and you aren't actually utilizing any trademarks, just passing the info through.

I do realize however that this may not be something that will be entertained or implemented, I just wanted to mention it.
