### ISSUE TITLE
Convert Discord RPC to Discord Game SDK

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [SayakMukhopadhyay/EDMC-Discord-Presence#13]
Need to use the latest Discord Game SDK library instead of the deprecated Discord RPC library

**Comment by Kyrluckechuck** [comment]
Since this is now just about a year ago, just wanted to check in if you think you will have any plans to get to this in the near future?

**Comment by SayakMukhopadhyay** [comment]
I have been busy at my work and this would involve making substantial changes so I haven't been able to pick this up but it is certainly something that I want to do.

**Comment by SayakMukhopadhyay** [comment]
Closed by 37c1ea884af1cd452cd8f51ac225bf4d51db01ef
