### ISSUE TITLE
Have the plugin display "Elite Dangerous" instead of "EDMC Discord Presence"

### ISSUE THREAD

**Issue by DanForever** [SayakMukhopadhyay/EDMC-Discord-Presence#20]

**Comment by keysmashes** [comment]
see #1

**Comment by DanForever** [comment]
Ah right, that sucks.
What if instead, there's a text field option in settings for the user to put whatever they want? Would that get around any legal problems?

**Comment by keysmashes** [comment]
see #5

> It's not really possible to make it an editable field unfortunately.

**Comment by c-stella** [comment]
I don't know if it's illegal to do so, but you can just edit load.py's 33th line 
`CLIENT_ID = b'386149818227097610'`
to
`CLIENT_ID = b'363413225578037248'`
so you'll get Elite Dangerous instead of EDMC Discord Presence.

**Comment by SayakMukhopadhyay** [comment]
I just want to jump in and say that IANAL and I have no idea if its illegal or not so I am not liable for anyone changing IDs of the plugin. But its an open source project so anyone can take the source code and deploy it as their own plugin.
