### ISSUE TITLE
Latest release tag only has source packages no compiled .zip

### ISSUE THREAD

**Issue by feczo** [SayakMukhopadhyay/EDMC-Discord-Presence#23]
instructions say "Download the latest version of the plugin from here. Make sure to download the release .zip and not the source code bundle."

going to the link from this step
https://github.com/SayakMukhopadhyay/EDMC-Discord-Presence/releases

latest release reads:
Latest release
 v2.1.2
 34b977c
Icarus
@SayakMukhopadhyay SayakMukhopadhyay released this 13 days ago

Added Portuguese (Brazil) translations

Assets
2
Source code
(zip)
Source code
(tar.gz)

only two assets while others have a 3rd DiscordPresence.zip

**Comment by SayakMukhopadhyay** [comment]
Oops, my bad. Fixed it.
