### ISSUE TITLE
Doesn't work without connection to FDev?

### ISSUE THREAD

**Issue by iEx5** [SayakMukhopadhyay/EDMC-Discord-Presence#3]
Since last update EDMC cannot connect to auth servers,and without that D-presence wont work in discord,
Is there any fix?im not good with python so i couldnt figure it out...
Seems like 'journal_entry' is not commiting

**Comment by SayakMukhopadhyay** [comment]
Hmm...the Discord Presence should work fine without CAPI but I have received reports from people who cannot get EDMC to work at all. I will take a look

**Comment by VackerSimon** [comment]
@SayakMukhopadhyay  EDMC works for me (says "Frontier server is down" but works fine anyway) but I don't see anything in Discord other than that I'm playing the game like normal

**Comment by VackerSimon** [comment]
Oh apparently EDMC needs to run as admin for this plugin to work? Because that fixed it

**Comment by SayakMukhopadhyay** [comment]
Thanks for the tip @VackerSimon . Also, a new version of EDMC has been released with the new authentication support. @iEx5 Could you see if the issue persists with the new release or not?

**Comment by iEx5** [comment]
Seems like fine now,just looks like 'journal_entry' happends only when cmdr is logged in

**Comment by SayakMukhopadhyay** [comment]
Ah! That could be the case. Glad it works now. I am closing the issue.
